[project]
name = "data-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Muhammad Sohail", email = "msohailbuzdar42@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.43.98",
    "celery>=5.6.3",
    "fastapi>=0.141.1",
    "httpx",
    "openpyxl>=3.1.5",
    "pandas>=3.0.6",
    "polars",
    "pyarrow>=25.0.1",
    "pydantic>=2.13.5",
    "pytest",
    "pytest-asyncio",
    "pytest-mock",
    "python-dotenv>=1.2.3",
    "redis>=8.1.0",
    "requests",
    "uvicorn>=0.53.0",
]

[project.scripts]
data-engine = "data_engine:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
